### ISSUE TITLE
STD回环检测如何使用？

### ISSUE THREAD

**Issue by andlbdx** [LeeWhisper/LTAOM#1]
按照给的步骤运行，发现没有回环检测

**Comment by LeeWhisper** [comment]
> 按照给的步骤运行，发现没有回环检测

LTAOM算法，从港大的视频，以及我自己实际使用的效果来看，肯定是有回环优化的，需要机器人重复访问以前走过的地图。如果依旧无法进入回环，可以考虑将参数OverlapScoreThr改小，或者在重复位置多运动一会，算法内部要求连续两次内点大于设定阈值才会进入回环检测（这是为了避免出现假阳性现象）。

希望对你有一定帮助，祝好！

**Comment by andlbdx** [comment]
非常感谢你的回复，重新调整了参数OverlapScoreThr，设置成0.15，已经跑出来回环了。
